### ISSUE TITLE
Support (ignore?) custom options

### ISSUE THREAD

**Issue by pgirolami** [mafintosh/protocol-buffers-schema#34]
I'm using https://github.com/devongovett/protobuf-jsonschema which depends on this project to map protocol buffer IDLs to JSON schema. I also use https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema/ to generate a BigQuery schema.

This last part requires providing a table name via a custom option named _gen_bq_schema.table_name_ (see https://developers.google.com/protocol-buffers/docs/proto#options), for example

```
package foo;
import "bq_table_name.proto";

message Bar {
  option (gen_bq_schema.table_name) = "bar_table";

  message Nested {
    repeated int32 a = 1;
  }

  required int32 a = 1;
  optional Nested b = 2;
  repeated string c = 3;
}

```

At the moment, this fails:

```
/usr/local/lib/node_modules/protobuf-jsonschema/node_modules/protocol-buffers-schema/parse.js:90
        throw new Error('Unexpected token in message field: ' + tokens[0])
        ^

Error: Unexpected token in message field: en_bq_schema.table_name
    at onfield (/usr/local/lib/node_modules/protobuf-jsonschema/node_modules/protocol-buffers-schema/parse.js:90:15)
    at onmessagebody (/usr/local/lib/node_modules/protobuf-jsonschema/node_modules/protocol-buffers-schema/parse.js:161:26)
    at onmessage (/usr/local/lib/node_modules/protobuf-jsonschema/node_modules/protocol-buffers-schema/parse.js:210:14)
    at parse (/usr/local/lib/node_modules/protobuf-jsonschema/node_modules/protocol-buffers-schema/parse.js:583:30)
    at Compiler.open (/usr/local/lib/node_modules/protobuf-jsonschema/index.js:17:16)
    at new Compiler (/usr/local/lib/node_modules/protobuf-jsonschema/index.js:9:22)
    at module.exports (/usr/local/lib/node_modules/protobuf-jsonschema/index.js:192:18)
    at Command.<anonymous> (/usr/local/lib/node_modules/protobuf-jsonschema/cli.js:13:18)
    at Command.listener (/usr/local/lib/node_modules/protobuf-jsonschema/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
````

As far as I can tell, this could safely be ignored for now, just like the `reserved`keyword was yesterday

**Comment by mafintosh** [comment]
Ignoring is fine for now although it would be nice to actually expose `option` on the returned schema

**Comment by pgirolami** [comment]
Tested the new release, works as expected. Thanks for the quick work, appreciate it.
